name: NPM Publish

env:
  NODE_VERSION: 22

on:
  push:
    tags:
      - v*

jobs:
  build-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Update npm
        run: npm install -g npm@latest

      - run: npm i
      - run: npm run build

      - name: Publish to NPM
        run: npm publish
